version: '3'

services:
  api:
    image: node:21-alpine3.17
    volumes:
      - .:/app
    working_dir: "/app"
    command: npx nodemon src/server.js
    ports:
      - 3030:3030
    depends_on:
      - mongo
  test:
    image: node:21-alpine3.17
    volumes:
      - .:/app
    working_dir: "/app"
    command: npm run test
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5
    volumes:
      - ../one2ten-data/db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test
      
