name: Run Docker Compose Service

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: 6.0.5
        mongodb-port: 27017
        mongodb-db: test
        mongodb-username: test
        mongodb-password: test

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: move .env.sample to .env
      run: mv .env.sample .env

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
