name: Run Docker Compose Service

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Rename .env.sample file to .env
      run: mv .env.sample .env

    - name: Run tests in containers
      run: docker-compose run --rm test npm install && npm test

    - name: Stop and remove services
      if: always()
      run: docker-compose down
